### ISSUE TITLE
Running Newman 3.4.3 getting error "Script execution timed out."

### ISSUE THREAD

**Issue by tranhungt** [postmanlabs/uvm#25] opened 2017-02-14 00:40 UTC
Midway through a newman collection run, the test suite prints "Script execution timed out." and exits the runner.
I traced the error message and seems to come from UVM.
Is this an indication that the node VM tried to boot up but took too long?

**Comment by shamasis** [comment] 2017-02-14 06:25
This usually occurs if you have an infinite loop in your scripts.

**Comment by tranhungt** [comment] 2017-02-14 07:37
Strange, the exact same postman collection consistently runs successfully on v3.2.0.

**Comment by czardoz** [comment] 2017-02-14 09:22
@tranhungt Could you share the stack trace?

**Comment by tranhungt** [comment] 2017-02-14 19:16
Unfortunately, there are no stack traces. I was only able to trace back the error message to UVM tests, with the text "Script execution timed out.".
Out of a 19-request suite, newman runs 10 and just exits.
It consistently fails at the same request though, possibly having issues with post-request test scripts.
For clarity, the http request itself passes, but in the post-request script, when I'm console logging information, it seems to fail consistently at the same place.

![image](https://cloud.githubusercontent.com/assets/4001160/22944392/6675ed74-f2a5-11e6-82c6-a33ba89810e3.png)


Here's my post-request  test script on the test case where it seems to be cutting off.
This particular request has a fairly large response size, about 27MB. I wonder if the xml2Json could be causing the timeout, since it's directly after the response time console log.

```
console.log("responseTime:", responseTime + "ms");
tests['status code 200'] = responseCode.code == 200;
var jsonObject = xml2Json(responseBody);
console.log(responseBody.substring(0,1000));
tests['parsing succeeds'] = jsonObject !== undefined;

 // city, state, payment options, neighborhood name and private party are coming as null for some of the listings
var schema = {
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "RestaurantFeed": {
      "type": "object",
      "properties": {
        "Restaurant": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "RestaurantID": {
                "type": "string"
              },
              "RestaurantName": {
                "type": "string"
              },
              "MetroName": {
                "type": "string"
              },
              "Address": {
                "type": "string"
              },
              "City": {
                "type": "string"
              },
              "PostalCode": {
                "type": "string"
              },
              "Phone": {
                "type": "string"
              },
              "PrimaryFoodType": {
                "type": "string"
              },
              "URL": {
                "type": "string"
              },
              "ReserveURL": {
                "type": "string"
              },
              "PaymentOptions": {
                "type": "string"
              },
              "MetroID": {
                "type": "string"
              },
              "CountryID": {
                "type": "string"
              },
              "Latitude": {
                "type": "string"
              },
              "Longitude": {
                "type": "string"
              },
              "RegionID": {
                "type": "string"
              },
              "RegionName": {
                "type": "string"
              },
              "NeighborhoodID": {
                "type": "string"
              },
              "FacebookURL": {
                "type": "string"
              },
              "NeighborhoodName": {
                "type": "string"
              },
              "Price": {
                "type": "string"
              },
              "PrivateParty": {
                "type": "string"
              }
            },
            "required": [
              "RestaurantID",
              "RestaurantName",
              "MetroName",
              "Address",
              "PostalCode",
              "Phone",
              "PrimaryFoodType",
              "ReserveURL",
              "MetroID",
              "CountryID",
              "Latitude",
              "Longitude",
              "RegionID",
              "RegionName",
              "NeighborhoodID"
            ]
          }
        }
      },
      "required": [
        "Restaurant"
      ]
    }
  },
  "required": [
    "RestaurantFeed"
  ]
};

tests["Valid schema"] = tv4.validate(jsonObject, schema);

console.log("feeds restaurant count:", jsonObject.RestaurantFeed.Restaurant.length);
```

**Comment by shamasis** [comment] 2017-02-14 20:07
Then you could increase the script execution timeout. I am on phone and don't recall the parameter off hand.

@kunagpal - can you also check whether in runtime v4 the script execution timeout property has been properly wired up or not.

**Comment by tranhungt** [comment] 2017-02-14 20:14
That would be super helpful, and most likely will fix the issue. I wasn't able to find that parameter anywhere in the docs. Could you please let me know what it is when you get the chance?

**Comment by tranhungt** [comment] 2017-02-21 22:52
@shamasis any updates on this?

**Comment by gmenyhert** [comment] 2017-03-30 14:09
I'm seeing this with 3.5.2 as well.  The only timeout setting (as far as I can tell) is for the request timeout which defaults to no timeout (infinity) so that clearly is not it.

I've verified that this doesn't seem to be actually related to the test execution as the tests all seem to be completing and reporting the correct status.  I put a branch in our script to ignore this particular error message and just move on.  I hate doing stuff like that but my only option seemed to be to not use newman anymore.

**Comment by KumG** [comment] 2017-04-13 14:14
I had the same problem when I was using an infinite loop in the tests, 

But now I have the error with another query (15MB response, also using the xml2Json method...)

Any idea?

**Comment by gmenyhert** [comment] 2017-04-13 15:39
With my scenario, the payload is JSON and not large at all.  One unusual thing I am doing is a busy wait in some of the tests because for a few of our tests, we need to wait a minute for an minutely update job to process some of the changes the API calls queued up.  I have not narrowed down the situation to see if that is the cause but regardless that (and other) tests all continue to work if you ignore this error so I'm having a tough time thinking that is actually the cause of the error.

**Comment by tranhungt** [comment] 2017-04-13 17:58
@gmenyhert so it sounds like in your test, waiting for 1 minute causes the execution timeout, which is the same error we see with other script executions that take too long.
So that gives more evidence that the problem lies in the current fixed time limit of the UVM execution scope.

**Comment by KumG** [comment] 2017-04-14 06:36
@gmenyhert I solved this problem (wait a minute) using a request to https://echo.getpostman.com/delay/10 and a loop using postman.setNextRequest(). A Javascript infinite loop immediatly cause the Timeout error.

**Comment by gmenyhert** [comment] 2017-04-14 15:42
@KumG - Thanks for the tip.  I spent the morning rewriting the waits and it worked a charm.

**Comment by czardoz** [comment] 2017-04-15 05:19
Quick note, echo.getpostman.com has moved to postman-echo.com :)

**Comment by shamasis** [comment] 2017-05-31 13:38
closing this.

**Closed by shamasis** 2017-05-31 13:38 UTC
